spring:
  profiles:
    active: dev

---

spring:
  profiles: dev  datasource:    hikari:      connection-timeout: 5000
      
client:
  ticketagent:
    address: http://localhost:9090/servicio/ws/helloworld
    
server:
  port: 9090  max-http-header-size: 20000
  connection-timeout: 3000


cxf:
  path: /servicio/ws

http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 512Mb
  
to.cxf: direct:addEmision

PathSftp: /INVOICE/DESARROLLO/
PathSftpFinal: _01/IN
to.factuInd: file:facturasIndividuales
to.xslt: file:xslts
to.xslt1: file:xslts
to.xslt2: xslt:file:xslts/xslt-2.xslt
to.xslt3: file:xslts
to.xslt4: file:xslts

ipJMS: 172.18.48.121
portJMS: 61616


